server:
  port: 8086

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/chat_app
    username: postgres
    password: 09122002
    driver-class-name: org.postgresql.Driver

#  CREATE TABLE tbl_user(
#  id BIGSERIAL PRIMARY KEY,
#  username VARCHAR,
#  password VARCHAR,
#  full_name VARCHAR,
#  image_url VARCHAR,
#  birthday TIMESTAMP,
#  gender VARCHAR
#  );

#  CREATE TABLE tbl_friend_request(
#  id BIGSERIAL PRIMARY KEY,
#  sender_id BIGINT REFERENCES tbl_user(id),
#  receiver_id BIGINT REFERENCES tbl_user(id),
#  created_at TIMESTAMP
#  );
#
#  CREATE TABLE tbl_friend_map(
#  id BIGSERIAL PRIMARY KEY,
#  user_id_1 BIGINT REFERENCES tbl_user(id),
#  user_id_2 BIGINT REFERENCES tbl_user(id)
#  )
#
#  CREATE TABLE tbl_post(
#  id BIGSERIAL PRIMARY KEY,
#  user_id BIGINT REFERENCES tbl_user(id),
#  content VARCHAR,
#  image_urls VARCHAR,
#  like_count INTEGER,
#  comment_count INTEGER,
#  share_count INTEGER,
#  share_id BIGINT REFERENCES tbl_post(id),
#  state VARCHAR,
#  created_at TIMESTAMP
#  )